export const CART_ACTION_TYPE = {
  SET_CART_OPEN: "cart/SET_CART_OPEN",
  SET_ITEM_TO_CART: "cart/SET_ITEM_TO_CART",
  SET_CART_COUNT: "cart/SET_CART_COUNT",
  SET_CART_TOTAL: "cart/SET_CART_TOTAL",
};
